import { Employee } from "../../types/tables";

export const employees: Employee[] = [
  {
    id_employee: 1,
    employee_name: "Jaime",
    employee_lastname: "Leon",
    employee_ci: "0203040506",
    employee_gender: "male",
    employee_born_date: new Date("1990-02-02"),
    employee_age: 35,
    employee_phone_number: "234-567-8901",
    employee_address: "123 Main St",
    username: "jleon",
    employee_email: "jaime.leon@example.com",
    employee_password: "1234",
    pin: "1231",
    role_id: 1,
    role: {
      id_role: 1,
      role_name: "admin",
      role_details: {
        id_role_details: 1,
        employee_id: 1,
        role_id: 1,
        details: null,
      },
    },
  },
  {
    id_employee: 2,
    employee_name: "Bruno Esteban",
    employee_lastname: "Bravo Zhunio",
    employee_ci: "0107425761",
    employee_gender: "hombre",
    employee_born_date: new Date("2003-10-28"),
    employee_age: 35,
    employee_phone_number: "096-339-7243",
    employee_address: "Baguanchi",
    username: "bebravo",
    employee_email: "bebravo@example.com",
    employee_password: "1234",
    pin: "1231",
    role_id: 1,
    role: {
      id_role: 1,
      role_name: "admin",
      role_details: {
        id_role_details: 2,
        employee_id: 2,
        role_id: 1,
        details: null,
      },
    },
  },
  {
    id_employee: 3,
    employee_name: "María Fernanda",
    employee_lastname: "Bravo Zhunio",
    employee_ci: "0123456789",
    employee_gender: "mujer",
    employee_born_date: new Date("1977-10-28"),
    employee_age: 35,
    employee_phone_number: "099-444-2408",
    employee_address: "Baguanchi",
    username: "mfbravo",
    employee_email: "mfbravo@example.com",
    employee_password: "1234",
    pin: "1231",
    role_id: 2,
    role: {
      id_role: 2,
      role_name: "emisor",
      role_details: {
        id_role_details: 3,
        employee_id: 3,
        role_id: 1,
        details: null,
      },
    },
  },
  {
    id_employee: 4,
    employee_name: "Bernarda Salome",
    employee_lastname: "Bravo Zhunio",
    employee_ci: "0987654321",
    employee_gender: "mujer",
    employee_born_date: new Date("2005-09-23"),
    employee_age: 35,
    employee_phone_number: "098-795-8762",
    employee_address: "Baguanchi",
    username: "bsbravo",
    employee_email: "bsbravo@example.com",
    employee_password: "1234",
    pin: "1231",
    role_id: 4,
    role: {
      id_role: 1,
      role_name: "admin",
      role_details: {
        id_role_details: 1,
        employee_id: 1,
        role_id: 1,
        details: null,
      },
    },
  },
  {
    id_employee: 5,
    employee_name: "María Eduarda",
    employee_lastname: "Bravo Zhunio",
    employee_ci: "0543216789",
    employee_gender: "mujer",
    employee_born_date: new Date("1999-08-31"),
    employee_age: 35,
    employee_phone_number: "098-609-1458",
    employee_address: "Baguanchi",
    username: "mebravo",
    employee_email: "mebravo@example.com",
    employee_password: "1234",
    pin: "1231",
    role_id: 3,
    role: {
      id_role: 1,
      role_name: "admin",
      role_details: {
        id_role_details: 1,
        employee_id: 1,
        role_id: 1,
        details: null,
      },
    },
  },
];
