export const pacientesData = [
  {
    turno: "Mañana",
    hora: "08:30",
    consultorio: "101",
    especialidad: "Cardiología",
    medico: "Dr. Juan Pérez",
    paciente: "Ana Gómez",
  },
  {
    turno: "Tarde",
    hora: "14:00",
    consultorio: "202",
    especialidad: "Dermatología",
    medico: "Dra. María López",
    paciente: "Carlos Martínez",
  },
  {
    turno: "Mañana",
    hora: "09:00",
    consultorio: "303",
    especialidad: "Pediatría",
    medico: "Dr. José Rodríguez",
    paciente: "Laura Pérez",
  },
  {
    turno: "Tarde",
    hora: "15:00",
    consultorio: "404",
    especialidad: "Ginecología",
    medico: "Dra. Ana Martínez",
    paciente: "Luis Gómez",
  },
  {
    turno: "Mañana",
    hora: "10:00",
    consultorio: "505",
    especialidad: "Neumología",
    medico: "Dr. Carlos López",
    paciente: "María Rodríguez",
  },
  {
    turno: "Tarde",
    hora: "16:00",
    consultorio: "606",
    especialidad: "Oftalmología",
    medico: "Dra. Laura Pérez",
    paciente: "Pedro Martínez",
  },
  {
    turno: "Mañana",
    hora: "11:00",
    consultorio: "707",
    especialidad: "Otorrinolaringología",
    medico: "Dr. Luis Gómez",
    paciente: "Sara Rodríguez",
  },
  {
    turno: "Tarde",
    hora: "17:00",
    consultorio: "808",
    especialidad: "Traumatología",
    medico: "Dra. Pedro López",
    paciente: "Sofía Martínez",
  },
  {
    turno: "Mañana",
    hora: "12:00",
    consultorio: "909",
    especialidad: "Urología",
    medico: "Dr. Sara Gómez",
    paciente: "Tomás Rodríguez",
  },
  {
    turno: "Tarde",
    hora: "18:00",
    consultorio: "1010",
    especialidad: "Psiquiatría",
    medico: "Dra. Sofía Pérez",
    paciente: "Víctor Martínez",
  },
];
